### ISSUE TITLE
"Wait" function doesn't work

### ISSUE THREAD

**Issue by adamlolgaming** [TechStreetDev/DFScript#40]
![obraz](https://github.com/DFOnline/DFScript/assets/94706391/aab0481d-21e0-4374-a816-3cec24b888c9)
"Wait" function doesn't work
![obraz](https://github.com/DFOnline/DFScript/assets/94706391/66207ee3-a2de-49b1-9d94-aa37f2343784)
(json script)
{"name":"Wait test","owner":"91c0ebcdeadc4c0091b94a46b63b7b7e","server":"None","description":"N/A","headers":[{"type":"event","event":"SEND_CHAT","snippet":{"parts":[{"type":"branch","condition":{"type":"condition","inverted":false,"condition":"IF_TEXT_CONTAINS"},"arguments":[{"type":"CLIENT_VALUE","value":"ENTERED_MESSAGE"},{"type":"TEXT","value":"this is a test if the wait is broken"}],"hasElse":false,"true":{"parts":[{"type":"action","action":"SEND_CHAT","arguments":[{"type":"TEXT","value":"Instant message (0s)"}]},{"type":"action","action":"WAIT","arguments":[{"type":"NUMBER","value":1.0}]},{"type":"action","action":"SEND_CHAT","arguments":[{"type":"TEXT","value":"omg wait works"}]}],"hidden":false},"false":{"parts":[],"hidden":false}}],"hidden":false}}],"config":[],"disabled":false,"version":5}

OS: Linux mint
Minecraft ver: 1.20.1
Mod ver: 83

**Comment by HellishBro** [comment]
is this still buggy or fixed already

**Comment by TechStreetDev** [comment]
Resolved
