### ISSUE TITLE
RecievedMessage returns text both with color and without color joined together

### ISSUE THREAD

**Issue by Speeder323** [TechStreetDev/DFScript#8]
Reposted from Discord, original poster: RedCommand#5228

1. Create a script that displays the received chat message on receive chat event
2. Wait for someone to send a message/send a message yourself

- Expected:
It shows the exact message that was sent (with colorcodes)

- Actual:
It sends a stripped version and the colorful version together
![image](https://user-images.githubusercontent.com/61844671/186744545-4e04c84f-541f-455c-9ad2-0a8ee0c54662.png)

PLEASE fix thank you

**Comment by TechStreetDev** [comment]
Hm im not sure why it does this

**Comment by GeorgeRNG** [comment]
@TechStreetDev fixed this in pr #9.
